### ISSUE TITLE
HTTP Error: 401 Client Error: 401 for url: https://www.eodms-sgdot.nrcan-rncan.gc.ca/wes/rapi/collections; attempting to connect again

### ISSUE THREAD

**Issue by willmacs** [eodms-sgdot/eodms-rapi-orderdownload#12]
### ISSUE

Listing collections errors out

### CAUSE

New version of underlying WES product changed this.

### SOLUTION

Add HTTP AUTH to this call.

### JUSTIFICATION

While the vendor could restore this not require AUTH, a logged in user intending to download ought to be able to HTTP AUTH to get logged-in list of collections (i.e. more data), not collections available to guest users

**Comment by mneige** [comment]
The error persists

**Comment by willmacs** [comment]
run "pip install requirements" in the orderdownload folder. The error is now fixed in the api package not this client package.

**Comment by mneige** [comment]
I already did

**Comment by keballantyne** [comment]
Remove your username and password from the config.ini file, run the script and enter your EODMS credentials when prompted.

**Comment by mneige** [comment]
Hi Kevin, I did it but still got the same error

**Comment by willmacs** [comment]
Provide your logs to eodms-sgdot@nrcan-rncan.gc.ca

**Comment by keballantyne** [comment]
Run "pip install py-eodms-rapi==1.3.0" to get the latest Python package

**Comment by mneige** [comment]
HI now I am running a virtual environment on 3.9.11 and I get to run the script but no download. I ran the command line. I am sending you my log, than you!

7 images returned from search results.
   ----------------------------------------------------------------
| EODMSRAPI | Getting list of current orders...

   0 existing orders found.
Submitting 7 orders.

| EODMSRAPI | Submitting order items...
| EODMSRAPI | Order submitted successfully.

| EODMSRAPI | Downloading images...
| EODMSRAPI | Getting list of current orders...
| EODMSRAPI | No orders could be found.

   -----Failed Downloads-------------------------------------------
   | The following images did not download:


Marie-Neige Beaudoin-Guérin

De : Kevin Ballantyne ***@***.***>
Envoyé : 7 avril 2022 16:22
À : eodms-sgdot/eodms-rapi-orderdownload ***@***.***>
Cc : MARIE-NEIGE BEAUDOIN-GUERIN ***@***.***>; Manual ***@***.***>
Objet : Re: [eodms-sgdot/eodms-rapi-orderdownload] HTTP Error: 401 Client Error: 401 for url: https://www.eodms-sgdot.nrcan-rncan.gc.ca/wes/rapi/collections; attempting to connect again (Issue #12)

Avertissement

Ce courriel provient de l'extérieur de l'organisation. Ne cliquez pas sur des liens ou n'ouvrez pas de pièces jointes à moins de connaître l'expéditeur ou de vous assurer que le contenu est légitime.

Run "pip install py-eodms-rapi==1.3.0" to get the latest Python package

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feodms-sgdot%2Feodms-rapi-orderdownload%2Fissues%2F12%23issuecomment-1092165723&data=04%7C01%7Cmarie-neige.beaudoin-guerin%40msp.gouv.qc.ca%7C2b879a2568414ef1f64108da18d433c4%7C9418e208c5854be3bbda50d4629ed1dd%7C0%7C0%7C637849596928548231%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=69PtLBwY11onveFD1ETzy75oejQTuEezkAn0gcsKSmM%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVRZLRQKKB7DEK4MCOKGVPLVD47UVANCNFSM5SWPGKYQ&data=04%7C01%7Cmarie-neige.beaudoin-guerin%40msp.gouv.qc.ca%7C2b879a2568414ef1f64108da18d433c4%7C9418e208c5854be3bbda50d4629ed1dd%7C0%7C0%7C637849596928548231%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ADUu9pa4cQmXQYMvPAeAkfqWH4YsYFILkWNAcCsTeME%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>


Avertissement

Ce message est confidentiel et est à l'usage exclusif du destinataire identifié ci-dessus. Toute autre personne est, par les présentes, avisée qu'il lui est strictement interdit de le diffuser, de le distribuer, d'en dévoiler le contenu ou de le reproduire. Si vous avez reçu cette communication par erreur, veuillez en informer l'expéditeur par courrier électronique immédiatement et détruire l'original de ce message ainsi que toute copie.

www.securitepublique.gouv.qc.ca <https://www.securitepublique.gouv.qc.ca>
